general:
    server: 69.33.0.216
    username: vpxuser
    password: Tubuai123!
logging:
    destination: ~/.psphere/psphere.log
    level: INFO # DEBUG, INFO, etc
vmware:
    datacenter: ICS Cloud Datacenter 5
    cluster: Development Cluster
    resourcePool: Customs-Dev-vDC